### PR TITLE
docs: add LICENSE file

### PR DESCRIPTION
**Pull request by sis0k0**
@LuceCarter, I've missed that while doing the initial review.

### CODE REVIEW

**Comment by MaBeuLux88** [comment]
Duplicated PR.

**Comment by sis0k0** [comment]
@MaBeuLux88 , this PR targets the 'finish' branch, whereas #3 targets 'main'.

**Comment by MaBeuLux88** [comment]
Oh :D !
They won't merge at some point? All good then ^^.

**Comment by sis0k0** [comment]
@MaBeuLux88, thanks for noticing the issue with the License file!

**Pull request merged**
